1559830530385	Sync.LogManager	DEBUG	Flushing file log
1559830530428	Sync.LogManager	DEBUG	Log cleanup threshold time: 1558966530428
1559830530544	Sync.LogManager	DEBUG	Done deleting files.
1559832436089	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559832436249	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559832436249	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559832436250	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559832436250	Sync.Service	INFO	Starting sync at 2019-06-06 16:47:16 in browser session DLDB2kz0MYXZ
1559832436250	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559832436252	Sync.Status	INFO	Resetting Status.
1559832436252	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559832436839	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559832437180	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559832437180	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559832437180	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559832437699	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559832438153	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559832438153	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559832438154	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559832438154	Sync.Service	INFO	Starting sync at 2019-06-06 16:47:18 in browser session DLDB2kz0MYXZ
1559832438169	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559832438170	Sync.Service	INFO	Cannot start sync: already syncing?
1559832438684	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559832441108	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://profile.accounts.firefox.com/v1/profile
1559832441108	Services.Common.RESTRequest	TRACE	Channel for GET https://profile.accounts.firefox.com/v1/profile returned status code 2152398862
1559832441108	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398862 - NS_ERROR_NET_TIMEOUT
1559832441108	Services.Common.RESTRequest	TRACE	GET body: 
1559832441108	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]"}
1559834350224	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559834350553	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559834350553	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559834350553	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559834350553	Sync.Service	INFO	Starting sync at 2019-06-06 17:19:10 in browser session DLDB2kz0MYXZ
1559834350553	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559834350553	Sync.Service	INFO	Cannot start sync: already syncing?
1559834350776	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559834351164	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559834351164	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559834351165	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559834351683	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559834352178	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559834352178	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559834352180	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559834352180	Sync.Service	INFO	Starting sync at 2019-06-06 17:19:12 in browser session DLDB2kz0MYXZ
1559834352184	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559834352184	Sync.Service	INFO	Cannot start sync: already syncing?
1559834352603	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559834352603	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559834352603	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559834352603	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559834352604	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559834352608	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
