1559644040805	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559645948198	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559645948282	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559645948282	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559645948285	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559645948285	Sync.Service	INFO	Starting sync at 2019-06-04 12:59:08 in browser session DLDB2kz0MYXZ
1559645948286	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559645948286	Sync.Status	INFO	Resetting Status.
1559645948287	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559645948761	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559645949311	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559645949311	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559645949312	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559645949691	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559645949961	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559645950307	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559645950307	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559645950308	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559645950308	Sync.Service	INFO	Starting sync at 2019-06-04 12:59:10 in browser session DLDB2kz0MYXZ
1559645950309	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559645950309	Sync.Service	INFO	Cannot start sync: already syncing?
1559646001125	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559646001125	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559646001125	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559646001126	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559646001127	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559646001130	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
