1559601732297	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559603647063	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559603647251	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559603647251	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559603647251	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559603647251	Sync.Service	INFO	Starting sync at 2019-06-04 01:14:07 in browser session DLDB2kz0MYXZ
1559603647252	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559603647255	Sync.Status	INFO	Resetting Status.
1559603647255	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559603647759	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559603648688	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559603649028	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559603649028	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559603649029	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559603649029	Sync.Service	INFO	Starting sync at 2019-06-04 01:14:09 in browser session DLDB2kz0MYXZ
1559603649029	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559603649029	Sync.Service	INFO	Cannot start sync: already syncing?
1559603650733	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559603651745	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://profile.accounts.firefox.com/v1/profile
1559603651745	Services.Common.RESTRequest	TRACE	Channel for GET https://profile.accounts.firefox.com/v1/profile returned status code 2152398862
1559603651745	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398862 - NS_ERROR_NET_TIMEOUT
1559603651745	Services.Common.RESTRequest	TRACE	GET body: 
1559603651745	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]"}
1559603651746	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_NET_TIMEOUT\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]"}
1559605569151	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559605569251	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559605569251	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559605569252	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559605569252	Sync.Service	INFO	Starting sync at 2019-06-04 01:46:09 in browser session DLDB2kz0MYXZ
1559605569252	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559605569252	Sync.Service	INFO	Cannot start sync: already syncing?
1559605569757	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559605570153	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559605570154	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559605570154	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559605570692	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559605571163	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559605571164	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559605571165	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559605571165	Sync.Service	INFO	Starting sync at 2019-06-04 01:46:11 in browser session DLDB2kz0MYXZ
1559605571169	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559605571170	Sync.Service	INFO	Cannot start sync: already syncing?
1559605571846	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559605580538	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559605580539	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559605580539	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559605580539	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559605580543	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559605580553	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
