1559724005729	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559725907127	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559725907248	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559725907248	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559725907249	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559725907249	Sync.Service	INFO	Starting sync at 2019-06-05 11:11:47 in browser session DLDB2kz0MYXZ
1559725907249	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559725907250	Sync.Status	INFO	Resetting Status.
1559725907250	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559725907751	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559725908185	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559725908185	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559725908185	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559725908733	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559725908835	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559725908835	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559725908836	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559725908836	Sync.Service	INFO	Starting sync at 2019-06-05 11:11:48 in browser session DLDB2kz0MYXZ
1559725908840	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559725908840	Sync.Service	INFO	Cannot start sync: already syncing?
1559725910186	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559727814112	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559727814253	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559727814253	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559727814254	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559727814254	Sync.Service	INFO	Starting sync at 2019-06-05 11:43:34 in browser session DLDB2kz0MYXZ
1559727814254	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559727814255	Sync.Service	INFO	Cannot start sync: already syncing?
1559727814749	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559727815185	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559727815185	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559727815186	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559727815668	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559727815668	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559727815669	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559727815669	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559727815670	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559727815676	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
