1559590235301	Sync.LogManager	DEBUG	Flushing file log
1559590235302	Services.Common.RESTRequest	TRACE	onStartRequest: GET https://profile.accounts.firefox.com/v1/profile
1559590235302	Services.Common.RESTRequest	TRACE	Channel for GET https://profile.accounts.firefox.com/v1/profile returned status code 2147500036
1559590235302	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2147500036 - NS_ERROR_ABORT
1559590235302	Services.Common.RESTRequest	TRACE	GET body: 
1559590235302	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_ABORT\"  nsresult: \"0x80004004 (NS_ERROR_ABORT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 434\"  data: no]"}
1559590235306	Sync.LogManager	DEBUG	Log cleanup threshold time: 1558726235306
1559590235314	Sync.LogManager	DEBUG	Done deleting files.
1559592126132	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559592126266	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559592126266	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559592126267	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559592126267	Sync.Service	INFO	Starting sync at 2019-06-03 22:02:06 in browser session DLDB2kz0MYXZ
1559592126267	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559592126268	Sync.Status	INFO	Resetting Status.
1559592126268	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559592126747	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559592126819	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1559592126820	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559592126820	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559592126820	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1559592126821	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559592126826	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
