1559636438371	Sync.LogManager	DEBUG	Flushing file log
1559636438389	Sync.LogManager	DEBUG	Log cleanup threshold time: 1558772438389
1559636438405	Sync.LogManager	DEBUG	Done deleting files.
1559638303103	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559638303249	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559638303249	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559638303249	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559638303249	Sync.Service	INFO	Starting sync at 2019-06-04 10:51:43 in browser session DLDB2kz0MYXZ
1559638303250	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559638303253	Sync.Status	INFO	Resetting Status.
1559638303253	Sync.Status	DEBUG	Status.service: error.sync.failed_partial => success.status_ok
1559638303752	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559638303826	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1559638303826	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559638303826	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559638303827	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1559638303827	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559638303831	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
